---
- name: disable apparmor
  service:
    name: apparmor # required. Name of the service.
    use: auto # not required. The service module actually uses system specific modules, normally through auto detection, this setting can force a specific module.,Normally it uses the value of the 'ansible_service_mgr' fact and falls back to the old 'service' module when none matching is found.
    enabled: false # not required. Whether the service should start on boot. B(At least one of state and enabled are required.)
    state: stoped # not required. choices: reloaded;restarted;started;stopped. C(started)/C(stopped) are idempotent actions that will not run commands unless necessary.  C(restarted) will always bounce the service.  C(reloaded) will always reload. B(At least one of state and enabled are required.) Note that reloaded will start the service if it is not already started, even if your chosen init system wouldn't normally.
  become: true

- name: Install common-packages
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
  become: true

- name: Add an Apt signing key, for mariadb url
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present
  become: true

- apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://mariadb.nethub.com.hk/repo/10.4/ubuntu bionic main
    state: present
  become: true

- name: Install mariadb
  apt:
    pkg: 
    - mariadb-client
    - mariadb-server
    - galera-4
    state: present
    update_cache: yes
  become: true

